import { Inter } from "next/font/google"
import "bulma/css/bulma.min.css"
import { AuthProvider } from "@/contexts/authContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Ultimate Reviewer",
  description: "Ultimate Reviewer, generated by create next app.",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  )
}
